//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 09:17:59 PM MSK 
//


package com.company;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ConfigurationFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ConfigurationFactory {


    /**
     * Create a new ConfigurationFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ConfigurationFactory() {
    }

    /**
     * Create an instance of {@link ConfigurationObject }
     * 
     */
    public ConfigurationObject createMetaDataObject() {
        return new ConfigurationObject();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration }
     * 
     */
    public ConfigurationObject.Configuration createMetaDataObjectConfiguration() {
        return new ConfigurationObject.Configuration();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties }
     * 
     */
    public ConfigurationObject.Configuration.Properties createMetaDataObjectConfigurationProperties() {
        return new ConfigurationObject.Configuration.Properties();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions }
     * 
     */
    public ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions createMetaDataObjectConfigurationPropertiesRequiredMobileApplicationPermissions() {
        return new ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair }
     * 
     */
    public ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair createMetaDataObjectConfigurationPropertiesRequiredMobileApplicationPermissionsPair() {
        return new ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.UsePurposes }
     * 
     */
    public ConfigurationObject.Configuration.Properties.UsePurposes createMetaDataObjectConfigurationPropertiesUsePurposes() {
        return new ConfigurationObject.Configuration.Properties.UsePurposes();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.InternalInfo }
     * 
     */
    public ConfigurationObject.Configuration.InternalInfo createMetaDataObjectConfigurationInternalInfo() {
        return new ConfigurationObject.Configuration.InternalInfo();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.InternalInfo.ContainedObject }
     * 
     */
    public ConfigurationObject.Configuration.InternalInfo.ContainedObject createMetaDataObjectConfigurationInternalInfoContainedObject() {
        return new ConfigurationObject.Configuration.InternalInfo.ContainedObject();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.ChildObjects }
     * 
     */
    public ConfigurationObject.Configuration.ChildObjects createMetaDataObjectConfigurationChildObjects() {
        return new ConfigurationObject.Configuration.ChildObjects();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Key }
     * 
     */
    public ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Key createMetaDataObjectConfigurationPropertiesRequiredMobileApplicationPermissionsPairKey() {
        return new ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Key();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Value }
     * 
     */
    public ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Value createMetaDataObjectConfigurationPropertiesRequiredMobileApplicationPermissionsPairValue() {
        return new ConfigurationObject.Configuration.Properties.RequiredMobileApplicationPermissions.Pair.Value();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.Properties.UsePurposes.Value }
     * 
     */
    public ConfigurationObject.Configuration.Properties.UsePurposes.Value createMetaDataObjectConfigurationPropertiesUsePurposesValue() {
        return new ConfigurationObject.Configuration.Properties.UsePurposes.Value();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.InternalInfo.ContainedObject.ClassId }
     * 
     */
    public ConfigurationObject.Configuration.InternalInfo.ContainedObject.ClassId createMetaDataObjectConfigurationInternalInfoContainedObjectClassId() {
        return new ConfigurationObject.Configuration.InternalInfo.ContainedObject.ClassId();
    }

    /**
     * Create an instance of {@link ConfigurationObject.Configuration.InternalInfo.ContainedObject.ObjectId }
     * 
     */
    public ConfigurationObject.Configuration.InternalInfo.ContainedObject.ObjectId createMetaDataObjectConfigurationInternalInfoContainedObjectObjectId() {
        return new ConfigurationObject.Configuration.InternalInfo.ContainedObject.ObjectId();
    }

}
