//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 01:36:17 AM MSK 
//


package com.company;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScheduledJob">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Properties">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Synonym">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="item">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="lang">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="content">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="MethodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Predefined" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RestartCountOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="RestartIntervalOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scheduledJob"
})
@XmlRootElement(name = "MetaDataObject", namespace = "http://v8.1c.ru/8.3/MDClasses")
public class ScheduledJobsObject {

    @XmlElement(name = "ScheduledJob", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
    protected ScheduledJobsObject.ScheduledJob scheduledJob;

    /**
     * Gets the value of the scheduledJob property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledJobsObject.ScheduledJob }
     *     
     */
    public ScheduledJobsObject.ScheduledJob getScheduledJob() {
        return scheduledJob;
    }

    /**
     * Sets the value of the scheduledJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledJobsObject.ScheduledJob }
     *     
     */
    public void setScheduledJob(ScheduledJobsObject.ScheduledJob value) {
        this.scheduledJob = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Properties">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Synonym">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="item">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="lang">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="content">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="MethodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Predefined" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RestartCountOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="RestartIntervalOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "properties"
    })
    public static class ScheduledJob {

        @XmlElement(name = "Properties", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
        protected ScheduledJobsObject.ScheduledJob.Properties properties;
        @XmlAttribute(name = "uuid")
        protected String uuid;

        /**
         * Gets the value of the properties property.
         * 
         * @return
         *     possible object is
         *     {@link ScheduledJobsObject.ScheduledJob.Properties }
         *     
         */
        public ScheduledJobsObject.ScheduledJob.Properties getProperties() {
            return properties;
        }

        /**
         * Sets the value of the properties property.
         * 
         * @param value
         *     allowed object is
         *     {@link ScheduledJobsObject.ScheduledJob.Properties }
         *     
         */
        public void setProperties(ScheduledJobsObject.ScheduledJob.Properties value) {
            this.properties = value;
        }

        /**
         * Gets the value of the uuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUuid() {
            return uuid;
        }

        /**
         * Sets the value of the uuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUuid(String value) {
            this.uuid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Synonym">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="item">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="lang">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="content">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="MethodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Predefined" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RestartCountOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="RestartIntervalOnFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "synonym",
            "comment",
            "methodName",
            "description",
            "key",
            "use",
            "predefined",
            "restartCountOnFailure",
            "restartIntervalOnFailure"
        })
        public static class Properties {

            @XmlElement(name = "Name", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected String name;
            @XmlElement(name = "Synonym", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected ScheduledJobsObject.ScheduledJob.Properties.Synonym synonym;
            @XmlElement(name = "Comment", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected Object comment;
            @XmlElement(name = "MethodName", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected String methodName;
            @XmlElement(name = "Description", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected Object description;
            @XmlElement(name = "Key", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected Object key;
            @XmlElement(name = "Use", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected String use;
            @XmlElement(name = "Predefined", required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected String predefined;
            @XmlElement(name = "RestartCountOnFailure", namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected int restartCountOnFailure;
            @XmlElement(name = "RestartIntervalOnFailure", namespace = "http://v8.1c.ru/8.3/MDClasses")
            protected int restartIntervalOnFailure;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the synonym property.
             * 
             * @return
             *     possible object is
             *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym }
             *     
             */
            public ScheduledJobsObject.ScheduledJob.Properties.Synonym getSynonym() {
                return synonym;
            }

            /**
             * Sets the value of the synonym property.
             * 
             * @param value
             *     allowed object is
             *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym }
             *     
             */
            public void setSynonym(ScheduledJobsObject.ScheduledJob.Properties.Synonym value) {
                this.synonym = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setComment(Object value) {
                this.comment = value;
            }

            /**
             * Gets the value of the methodName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMethodName() {
                return methodName;
            }

            /**
             * Sets the value of the methodName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMethodName(String value) {
                this.methodName = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setDescription(Object value) {
                this.description = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setKey(Object value) {
                this.key = value;
            }

            /**
             * Gets the value of the use property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUse() {
                return use;
            }

            /**
             * Sets the value of the use property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUse(String value) {
                this.use = value;
            }

            /**
             * Gets the value of the predefined property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPredefined() {
                return predefined;
            }

            /**
             * Sets the value of the predefined property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPredefined(String value) {
                this.predefined = value;
            }

            /**
             * Gets the value of the restartCountOnFailure property.
             * 
             */
            public int getRestartCountOnFailure() {
                return restartCountOnFailure;
            }

            /**
             * Sets the value of the restartCountOnFailure property.
             * 
             */
            public void setRestartCountOnFailure(int value) {
                this.restartCountOnFailure = value;
            }

            /**
             * Gets the value of the restartIntervalOnFailure property.
             * 
             */
            public int getRestartIntervalOnFailure() {
                return restartIntervalOnFailure;
            }

            /**
             * Sets the value of the restartIntervalOnFailure property.
             * 
             */
            public void setRestartIntervalOnFailure(int value) {
                this.restartIntervalOnFailure = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="item">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="lang">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="content">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "item"
            })
            public static class Synonym {

                @XmlElement(required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
                protected ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item item;

                /**
                 * Gets the value of the item property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item }
                 *     
                 */
                public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item getItem() {
                    return item;
                }

                /**
                 * Sets the value of the item property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item }
                 *     
                 */
                public void setItem(ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item value) {
                    this.item = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="lang">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="content">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "lang",
                    "content"
                })
                public static class Item {

                    @XmlElement(required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
                    protected String name;
                    @XmlElement(required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
                    protected ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang lang;
                    @XmlElement(required = true, namespace = "http://v8.1c.ru/8.3/MDClasses")
                    protected ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content content;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the lang property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang }
                     *     
                     */
                    public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang getLang() {
                        return lang;
                    }

                    /**
                     * Sets the value of the lang property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang }
                     *     
                     */
                    public void setLang(ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang value) {
                        this.lang = value;
                    }

                    /**
                     * Gets the value of the content property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content }
                     *     
                     */
                    public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content getContent() {
                        return content;
                    }

                    /**
                     * Sets the value of the content property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content }
                     *     
                     */
                    public void setContent(ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content value) {
                        this.content = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Content {

                        @XmlAttribute(name = "name")
                        protected String name;
                        @XmlAttribute(name = "type")
                        protected String type;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the type property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getType() {
                            return type;
                        }

                        /**
                         * Sets the value of the type property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setType(String value) {
                            this.type = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Lang {

                        @XmlAttribute(name = "name")
                        protected String name;
                        @XmlAttribute(name = "type")
                        protected String type;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the type property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getType() {
                            return type;
                        }

                        /**
                         * Sets the value of the type property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setType(String value) {
                            this.type = value;
                        }

                    }

                }

            }

        }

    }

}
