//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 01:36:17 AM MSK 
//


package com.company;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ScheduledJobsFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ScheduledJobsFactory {


    /**
     * Create a new ScheduledJobsFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ScheduledJobsFactory() {
    }

    /**
     * Create an instance of {@link ScheduledJobsObject }
     * 
     */
    public ScheduledJobsObject createMetaDataObject() {
        return new ScheduledJobsObject();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob }
     * 
     */
    public ScheduledJobsObject.ScheduledJob createMetaDataObjectScheduledJob() {
        return new ScheduledJobsObject.ScheduledJob();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob.Properties }
     * 
     */
    public ScheduledJobsObject.ScheduledJob.Properties createMetaDataObjectScheduledJobProperties() {
        return new ScheduledJobsObject.ScheduledJob.Properties();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym }
     * 
     */
    public ScheduledJobsObject.ScheduledJob.Properties.Synonym createMetaDataObjectScheduledJobPropertiesSynonym() {
        return new ScheduledJobsObject.ScheduledJob.Properties.Synonym();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item }
     * 
     */
    public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item createMetaDataObjectScheduledJobPropertiesSynonymItem() {
        return new ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang }
     * 
     */
    public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang createMetaDataObjectScheduledJobPropertiesSynonymItemLang() {
        return new ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Lang();
    }

    /**
     * Create an instance of {@link ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content }
     * 
     */
    public ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content createMetaDataObjectScheduledJobPropertiesSynonymItemContent() {
        return new ScheduledJobsObject.ScheduledJob.Properties.Synonym.Item.Content();
    }

}
